/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 82104
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLine = new javax.swing.JTextField();
        lblMemory = new javax.swing.JLabel();
        btnBackSpace = new javax.swing.JButton();
        btnClearError = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnMemoryClear = new javax.swing.JButton();
        btnMemoryRecall = new javax.swing.JButton();
        btnMemoryStore = new javax.swing.JButton();
        btnMemoryAdd = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnPM = new javax.swing.JButton();
        btnMinuse = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnPer = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("계산기");

        txtLine.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLine.setText("0.");

        lblMemory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnBackSpace.setForeground(java.awt.Color.red);
        btnBackSpace.setText("Backspace");
        btnBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSpaceActionPerformed(evt);
            }
        });

        btnClearError.setForeground(java.awt.Color.red);
        btnClearError.setText("CE");
        btnClearError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearErrorActionPerformed(evt);
            }
        });

        btnClear.setForeground(java.awt.Color.red);
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnMemoryClear.setForeground(java.awt.Color.red);
        btnMemoryClear.setText("MC");
        btnMemoryClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryClearActionPerformed(evt);
            }
        });

        btnMemoryRecall.setForeground(java.awt.Color.red);
        btnMemoryRecall.setText("MR");
        btnMemoryRecall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryRecallActionPerformed(evt);
            }
        });

        btnMemoryStore.setForeground(java.awt.Color.red);
        btnMemoryStore.setText("MS");
        btnMemoryStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryStoreActionPerformed(evt);
            }
        });

        btnMemoryAdd.setForeground(java.awt.Color.red);
        btnMemoryAdd.setText("M+");
        btnMemoryAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryAddActionPerformed(evt);
            }
        });

        btn7.setForeground(java.awt.Color.blue);
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn4.setForeground(java.awt.Color.blue);
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn1.setForeground(java.awt.Color.blue);
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn0.setForeground(java.awt.Color.blue);
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn8.setForeground(java.awt.Color.blue);
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn5.setForeground(java.awt.Color.blue);
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn2.setForeground(java.awt.Color.blue);
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btnPM.setForeground(java.awt.Color.blue);
        btnPM.setText("+/-");
        btnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMActionPerformed(evt);
            }
        });

        btnMinuse.setForeground(java.awt.Color.red);
        btnMinuse.setText("-");
        btnMinuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinuseActionPerformed(evt);
            }
        });

        btnPlus.setForeground(java.awt.Color.red);
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btn9.setForeground(java.awt.Color.blue);
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn6.setForeground(java.awt.Color.blue);
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn3.setForeground(java.awt.Color.blue);
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnDot.setForeground(java.awt.Color.blue);
        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btnDiv.setForeground(java.awt.Color.red);
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnMul.setForeground(java.awt.Color.red);
        btnMul.setText("*");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });

        btnSqrt.setForeground(java.awt.Color.blue);
        btnSqrt.setText("sqrt");
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });

        btnPer.setForeground(java.awt.Color.blue);
        btnPer.setText("%");
        btnPer.setToolTipText("");
        btnPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerActionPerformed(evt);
            }
        });

        btnLog.setForeground(java.awt.Color.blue);
        btnLog.setText("1/x");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnResult.setForeground(java.awt.Color.red);
        btnResult.setText("=");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMemoryStore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(btnMemoryRecall, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(btnMemoryClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(btnMemoryAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnMinuse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnPer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLine)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearError, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMemory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClearError, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addComponent(btnBackSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMemoryClear, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMemoryRecall, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMemoryStore, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMemoryAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPM, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDot, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMul, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMinuse, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPer, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLog, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResult, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(btnDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSqrt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(113, 113, 113)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double dNum1 = 0;  // 안쪽 입력값
    double dNum2 = 0;  // 현재값
    String sOpr = "";  // 연산자값
    boolean bDot = false; // . 입력 판단
    double dMem = 0; // 메모리값
    
    String sMinu = "";
    
    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        if(bDot == false){
            if(dNum2 == 0 && sMinu.equals("")){
                txtLine.setText(btn0.getText());
            }else{
                txtLine.setText(txtLine.getText() + btn0.getText());
            }
        }else if(bDot == true){
            txtLine.setText(txtLine.getText() + btn0.getText());
        }
        dNum2 = Double.parseDouble(txtLine.getText());
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if(bDot == false){
            if(dNum2 == 0 && sMinu.equals("")){
                txtLine.setText(btn1.getText());
            }else{
                txtLine.setText(txtLine.getText() + btn1.getText());
            }
        }else if(bDot == true){
            txtLine.setText(txtLine.getText() + btn1.getText());
        }
        dNum2 = Double.parseDouble(txtLine.getText());
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if(bDot == false){
            if(dNum2 == 0 && sMinu.equals("")){
                txtLine.setText(btn2.getText());
            }else{
                txtLine.setText(txtLine.getText() + btn2.getText());
            }
        }else if(bDot == true){
            txtLine.setText(txtLine.getText() + btn2.getText());
        }
        dNum2 = Double.parseDouble(txtLine.getText());
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if(bDot == false){
            if(dNum2 == 0 && sMinu.equals("")){
                txtLine.setText(btn3.getText());
            }else{
                txtLine.setText(txtLine.getText() + btn3.getText());
            }
        }else if(bDot == true){
            txtLine.setText(txtLine.getText() + btn3.getText());
        }
        dNum2 = Double.parseDouble(txtLine.getText());
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if(bDot == false){
            if(dNum2 == 0 && sMinu.equals("")){
                txtLine.setText(btn4.getText());
            }else{
                txtLine.setText(txtLine.getText() + btn4.getText());
            }
        }else if(bDot == true){
            txtLine.setText(txtLine.getText() + btn4.getText());
        }
        dNum2 = Double.parseDouble(txtLine.getText());
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if(bDot == false){
            if(dNum2 == 0 && sMinu.equals("")){
                txtLine.setText(btn5.getText());
            }else{
                txtLine.setText(txtLine.getText() + btn5.getText());
            }
        }else if(bDot == true){
            txtLine.setText(txtLine.getText() + btn5.getText());
        }
        dNum2 = Double.parseDouble(txtLine.getText());
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if(bDot == false){
            if(dNum2 == 0 && sMinu.equals("")){
                txtLine.setText(btn6.getText());
            }else{
                txtLine.setText(txtLine.getText() + btn6.getText());
            }
        }else if(bDot == true){
            txtLine.setText(txtLine.getText() + btn6.getText());
        }
        dNum2 = Double.parseDouble(txtLine.getText());
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if(bDot == false){
            if(dNum2 == 0 && sMinu.equals("")){
                txtLine.setText(btn7.getText());
            }else{
                txtLine.setText(txtLine.getText() + btn7.getText());
            }
        }else if(bDot == true){
            txtLine.setText(txtLine.getText() + btn7.getText());
        }
        dNum2 = Double.parseDouble(txtLine.getText());
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if(bDot == false){
            if(dNum2 == 0 && sMinu.equals("")){
                txtLine.setText(btn8.getText());
            }else{
                txtLine.setText(txtLine.getText() + btn8.getText());
            }
        }else if(bDot == true){
            txtLine.setText(txtLine.getText() + btn8.getText());
        }
        dNum2 = Double.parseDouble(txtLine.getText());
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if(bDot == false){
            if(dNum2 == 0 && sMinu.equals("")){
                txtLine.setText(btn9.getText());
            }else{
                txtLine.setText(txtLine.getText() + btn9.getText());
            }
        }else if(bDot == true){
            txtLine.setText(txtLine.getText() + btn9.getText());
        }
        dNum2 = Double.parseDouble(txtLine.getText());
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSpaceActionPerformed
        // TODO add your handling code here:
        String sTemp = "";
        char[] cLines = txtLine.getText().toCharArray();
        
        if(cLines.length > 0){
            if(cLines[cLines.length-1] == '.'){
                bDot = false;
            }
            
            for(int i = 0; i < cLines.length-1; i++){
                sTemp += cLines[i];
            }
            
            txtLine.setText(sTemp);
            dNum2 = Double.parseDouble(txtLine.getText());
        }
    }//GEN-LAST:event_btnBackSpaceActionPerformed

    private void btnClearErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearErrorActionPerformed
        // TODO add your handling code here:
        if(dNum2 != 0){
            dNum2 = 0;
            txtLine.setText(Integer.toString((int)dNum2));
            bDot = false;
        }
    }//GEN-LAST:event_btnClearErrorActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        dNum1 = 0;
        dNum2 = 0;
        txtLine.setText("0.");
        bDot = false;
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMActionPerformed
        // TODO add your handling code here:
        if(dNum2 != 0){
            if((dNum2 - (int)dNum2) == 0){
                dNum2 *= -1;
                txtLine.setText(Integer.toString((int)dNum2));
            }else{
                dNum2 *= -1;
                txtLine.setText(Double.toString(dNum2));
            }
        }
        
        if(!(sOpr.equals(""))){  // 연산자를 누른 후
            if(dNum2 == 0){
                sMinu = "-";
                txtLine.setText(sMinu);
            }else{
                sMinu = "";
                txtLine.setText(sMinu);
            }
        }
    }//GEN-LAST:event_btnPMActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        // TODO add your handling code here:
        if(bDot ==  true){
            return;
        }
        
        if(bDot == false && !txtLine.getText().equals("0.")){
            if(txtLine.getText().isEmpty()){
                txtLine.setText("0");
            }
            
            txtLine.setText(txtLine.getText() + ".");
            bDot = true;
        }else if(bDot == false && txtLine.getText().equals("0.")){
            dNum2 = Double.parseDouble(txtLine.getText());
            bDot = true;
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnMemoryClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryClearActionPerformed
        // TODO add your handling code here:
        dMem = 0;
        lblMemory.setText(null);
    }//GEN-LAST:event_btnMemoryClearActionPerformed

    private void btnMemoryRecallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryRecallActionPerformed
        // TODO add your handling code here:
        dNum2 = dMem;
        if(dNum2 != 0){
            if((dNum2 - (int)dNum2) == 0){
                txtLine.setText(Integer.toString((int)dNum2));
            }else{
                txtLine.setText(Double.toString(dNum2));
            }
        }
    }//GEN-LAST:event_btnMemoryRecallActionPerformed

    private void btnMemoryStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryStoreActionPerformed
        // TODO add your handling code here:
        dMem = Double.parseDouble(txtLine.getText());
        lblMemory.setText(Double.toString(dMem));
    }//GEN-LAST:event_btnMemoryStoreActionPerformed

    private void btnMemoryAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryAddActionPerformed
        // TODO add your handling code here:
        dMem += Double.parseDouble(txtLine.getText());
        lblMemory.setText(Double.toString(dMem));
    }//GEN-LAST:event_btnMemoryAddActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        // TODO add your handling code here:
        if(dNum2 != 0){
            dNum2 = Math.sqrt(dNum2);
            txtLine.setText(Double.toString(dNum2));
        }
    }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerActionPerformed
        // TODO add your handling code here:
        if(sOpr.equals("") && dNum2 != 0){
            dNum2 = dNum2/100;
            txtLine.setText(Double.toString(dNum2));
        }
    }//GEN-LAST:event_btnPerActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        if(dNum2 != 0){
            dNum2 = 1/dNum2;
            txtLine.setText(Double.toString(dNum2));
        }
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        // TODO add your handling code here:
        double dRe; // 결과값
        switch(sOpr){
            case "+":
                dRe = dNum1 + dNum2;
                if((dRe - (int)dRe) == 0){
                    txtLine.setText(Integer.toString((int)dRe));
                }else{
                    txtLine.setText(Double.toString(dRe));
                }
                break;
            case "-":
                dRe = dNum1 - dNum2;
                if((dRe - (int)dRe) == 0){
                    txtLine.setText(Integer.toString((int)dRe));
                }else{
                    txtLine.setText(Double.toString(dRe));
                }
                break;
            case "*":
                dRe = dNum1 * dNum2;
                if((dRe - (int)dRe) == 0){
                    txtLine.setText(Integer.toString((int)dRe));
                }else{
                    txtLine.setText(Double.toString(dRe));
                }
                break;
            case "/":
                dRe = dNum1 / dNum2;
                if((dRe - (int)dRe) == 0){
                    txtLine.setText(Integer.toString((int)dRe));
                }else{
                    txtLine.setText(Double.toString(dRe));
                }
                break;
            default:
                break;
        }
        
        sOpr = "";
        dNum1 = 0;
        dNum2 = Double.parseDouble(txtLine.getText());
        sMinu = "";
    }//GEN-LAST:event_btnResultActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
        sOpr = "/";
        
        
        if(dNum1 == 0) {
            dNum1 = dNum2;
        }else if(dNum1 != 0){
            dNum1 = dNum1 / dNum2;
            if((dNum1 - (int)dNum1) == 0){
                txtLine.setText(Integer.toString((int)dNum1));
            }else{
                txtLine.setText(Double.toString(dNum1));
            }
        }
        
        dNum2 = 0;
        bDot = false;
        sMinu = "";
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        // TODO add your handling code here:
        sOpr = "*";
        
        
        if(dNum1 == 0) {
            dNum1 = dNum2;
        }else if(dNum1 != 0){
            dNum1 = dNum1 * dNum2;
            if((dNum1 - (int)dNum1) == 0){
                txtLine.setText(Integer.toString((int)dNum1));
            }else{
                txtLine.setText(Double.toString(dNum1));
            }
        }
        
        dNum2 = 0;
        bDot = false;
        sMinu = "";
    }//GEN-LAST:event_btnMulActionPerformed

    private void btnMinuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinuseActionPerformed
        // TODO add your handling code here:
        sOpr = "-";
        
        
        if(dNum1 == 0) {
            dNum1 = dNum2;
        }else if(dNum1 != 0){
            dNum1 = dNum1 - dNum2;
            if((dNum1 - (int)dNum1) == 0){
                txtLine.setText(Integer.toString((int)dNum1));
            }else{
                txtLine.setText(Double.toString(dNum1));
            }
        }
        
        dNum2 = 0;
        bDot = false;
        sMinu = "";
    }//GEN-LAST:event_btnMinuseActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
        sOpr = "+";
        
        
        if(dNum1 == 0) {
            dNum1 = dNum2;
        }else if(dNum1 != 0){
            dNum1 = dNum1 + dNum2;
            if((dNum1 - (int)dNum1) == 0){
                txtLine.setText(Integer.toString((int)dNum1));
            }else{
                txtLine.setText(Double.toString(dNum1));
            }
        }
        
        dNum2 = 0;
        bDot = false;
        sMinu = "";
    }//GEN-LAST:event_btnPlusActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBackSpace;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearError;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMemoryAdd;
    private javax.swing.JButton btnMemoryClear;
    private javax.swing.JButton btnMemoryRecall;
    private javax.swing.JButton btnMemoryStore;
    private javax.swing.JButton btnMinuse;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnPM;
    private javax.swing.JButton btnPer;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JLabel lblMemory;
    private javax.swing.JTextField txtLine;
    // End of variables declaration//GEN-END:variables
}
